package org.kudytech.compras.ws.confsistema.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.kudytech.confsistema.ws.domain.ConfSistema;
import org.kudytech.ws.response.AbstractSimpleResponseMessageHybrid;
import org.kudytech.ws.response.AbstractSimpleResponseMessageHybridList;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.6-1b01 Generated
 * source version: 2.2
 *
 */
@WebService(name = "ConfSistemaWS", targetNamespace = "http://ws.webservices.confsistema.adeamx.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ConfSistemaWS {

    /**
     *
     * @param catalogo
     * @return returns
     * org.kudytech.compras.ws.confsistema.client.AbstractSimpleResponseMessageHybridList
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByCatalog", targetNamespace = "http://ws.webservices.confsistema.adeamx.com/", className = "org.kudytech.compras.ws.confsistema.client.FindByCatalog")
    @ResponseWrapper(localName = "findByCatalogResponse", targetNamespace = "http://ws.webservices.confsistema.adeamx.com/", className = "org.kudytech.compras.ws.confsistema.client.FindByCatalogResponse")
    @Action(input = "http://ws.webservices.confsistema.adeamx.com/ConfSistemaWS/findByCatalogRequest", output = "http://ws.webservices.confsistema.adeamx.com/ConfSistemaWS/findByCatalogResponse")
    public AbstractSimpleResponseMessageHybridList findByCatalog(
            @WebParam(name = "catalogo", targetNamespace = "") String catalogo);

    /**
     *
     * @param catalogo
     * @param variable
     * @return returns
     * org.kudytech.compras.ws.confsistema.client.AbstractSimpleResponseMessageHybrid
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByCatalogAndVariable", targetNamespace = "http://ws.webservices.confsistema.adeamx.com/", className = "org.kudytech.compras.ws.confsistema.client.FindByCatalogAndVariable")
    @ResponseWrapper(localName = "findByCatalogAndVariableResponse", targetNamespace = "http://ws.webservices.confsistema.adeamx.com/", className = "org.kudytech.compras.ws.confsistema.client.FindByCatalogAndVariableResponse")
    @Action(input = "http://ws.webservices.confsistema.adeamx.com/ConfSistemaWS/findByCatalogAndVariableRequest", output = "http://ws.webservices.confsistema.adeamx.com/ConfSistemaWS/findByCatalogAndVariableResponse")
    public AbstractSimpleResponseMessageHybrid findByCatalogAndVariable(
            @WebParam(name = "catalogo", targetNamespace = "") String catalogo,
            @WebParam(name = "variable", targetNamespace = "") String variable);

    /**
     *
     * @param catalogo
     * @param variable
     * @return returns
     * org.kudytech.compras.ws.confsistema.client.AbstractSimpleResponseMessageHybrid
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStringValueByCatalogAndVariable", targetNamespace = "http://ws.webservices.confsistema.adeamx.com/", className = "org.kudytech.compras.ws.confsistema.client.GetStringValueByCatalogAndVariable")
    @ResponseWrapper(localName = "getStringValueByCatalogAndVariableResponse", targetNamespace = "http://ws.webservices.confsistema.adeamx.com/", className = "org.kudytech.compras.ws.confsistema.client.GetStringValueByCatalogAndVariableResponse")
    @Action(input = "http://ws.webservices.confsistema.adeamx.com/ConfSistemaWS/getStringValueByCatalogAndVariableRequest", output = "http://ws.webservices.confsistema.adeamx.com/ConfSistemaWS/getStringValueByCatalogAndVariableResponse")
    public AbstractSimpleResponseMessageHybrid getStringValueByCatalogAndVariable(
            @WebParam(name = "catalogo", targetNamespace = "") String catalogo,
            @WebParam(name = "variable", targetNamespace = "") String variable);

    /**
     *
     * @param catalogo
     * @param variable
     * @return returns
     * org.kudytech.compras.ws.confsistema.client.AbstractSimpleResponseMessageHybrid
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNumberValueByatCalogAndVariable", targetNamespace = "http://ws.webservices.confsistema.adeamx.com/", className = "org.kudytech.compras.ws.confsistema.client.GetNumberValueByatCalogAndVariable")
    @ResponseWrapper(localName = "getNumberValueByatCalogAndVariableResponse", targetNamespace = "http://ws.webservices.confsistema.adeamx.com/", className = "org.kudytech.compras.ws.confsistema.client.GetNumberValueByatCalogAndVariableResponse")
    @Action(input = "http://ws.webservices.confsistema.adeamx.com/ConfSistemaWS/getNumberValueByatCalogAndVariableRequest", output = "http://ws.webservices.confsistema.adeamx.com/ConfSistemaWS/getNumberValueByatCalogAndVariableResponse")
    public AbstractSimpleResponseMessageHybrid getNumberValueByatCalogAndVariable(
            @WebParam(name = "catalogo", targetNamespace = "") String catalogo,
            @WebParam(name = "variable", targetNamespace = "") String variable);

    /**
     *
     * @param catalogo
     * @param variable
     * @return returns
     * org.kudytech.compras.ws.confsistema.client.AbstractSimpleResponseMessageHybrid
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDateValueByatCalogAndVariable", targetNamespace = "http://ws.webservices.confsistema.adeamx.com/", className = "org.kudytech.compras.ws.confsistema.client.GetDateValueByatCalogAndVariable")
    @ResponseWrapper(localName = "getDateValueByatCalogAndVariableResponse", targetNamespace = "http://ws.webservices.confsistema.adeamx.com/", className = "org.kudytech.compras.ws.confsistema.client.GetDateValueByatCalogAndVariableResponse")
    @Action(input = "http://ws.webservices.confsistema.adeamx.com/ConfSistemaWS/getDateValueByatCalogAndVariableRequest", output = "http://ws.webservices.confsistema.adeamx.com/ConfSistemaWS/getDateValueByatCalogAndVariableResponse")
    public AbstractSimpleResponseMessageHybrid getDateValueByatCalogAndVariable(
            @WebParam(name = "catalogo", targetNamespace = "") String catalogo,
            @WebParam(name = "variable", targetNamespace = "") String variable);

    /**
     *
     * @param catalogo
     * @param variable
     * @return returns
     * org.kudytech.compras.ws.confsistema.client.AbstractSimpleResponseMessageHybrid
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBlobValueByatCalogAndVariable", targetNamespace = "http://ws.webservices.confsistema.adeamx.com/", className = "org.kudytech.compras.ws.confsistema.client.GetBlobValueByatCalogAndVariable")
    @ResponseWrapper(localName = "getBlobValueByatCalogAndVariableResponse", targetNamespace = "http://ws.webservices.confsistema.adeamx.com/", className = "org.kudytech.compras.ws.confsistema.client.GetBlobValueByatCalogAndVariableResponse")
    @Action(input = "http://ws.webservices.confsistema.adeamx.com/ConfSistemaWS/getBlobValueByatCalogAndVariableRequest", output = "http://ws.webservices.confsistema.adeamx.com/ConfSistemaWS/getBlobValueByatCalogAndVariableResponse")
    public AbstractSimpleResponseMessageHybrid getBlobValueByatCalogAndVariable(
            @WebParam(name = "catalogo", targetNamespace = "") String catalogo,
            @WebParam(name = "variable", targetNamespace = "") String variable);

    /**
     *
     * @param confSistema
     * @return returns org.kudytech.compras.ws.confsistema.client.ConfSistema
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "testConfSistema", targetNamespace = "http://ws.webservices.confsistema.adeamx.com/", className = "org.kudytech.compras.ws.confsistema.client.TestConfSistema")
    @ResponseWrapper(localName = "testConfSistemaResponse", targetNamespace = "http://ws.webservices.confsistema.adeamx.com/", className = "org.kudytech.compras.ws.confsistema.client.TestConfSistemaResponse")
    @Action(input = "http://ws.webservices.confsistema.adeamx.com/ConfSistemaWS/testConfSistemaRequest", output = "http://ws.webservices.confsistema.adeamx.com/ConfSistemaWS/testConfSistemaResponse")
    public ConfSistema testConfSistema(
            @WebParam(name = "confSistema", targetNamespace = "") ConfSistema confSistema);
}
