package org.kudytech.adeamx.webmex.client;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import org.kudytech.ws.client.utils.AbstractWebServiceProvider;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.6-1b01 Generated
 * source version: 2.2
 *
 */
@WebServiceClient(name = "SeguridadWSService",
targetNamespace = "http://ws.webservices.seguridad.adeamx.com/",
wsdlLocation = "http://localhost:6680/adea-compras-ws/Seguridad?wsdl")
public class SeguridadWSService
        extends AbstractWebServiceProvider {

    private static QName SEGURIDADWSSERVICE_QNAME =
            new QName("http://ws.webservices.seguridad.adeamx.com/", "SeguridadWSService");
    private static final String LOCAL_PART = "SeguridadWS";
    private static String NAME_SPACE_URI = "http://ws.webservices.seguridad.adeamx.com/";
    private static final String WS_PORT="SeguridadWSPort";

    public SeguridadWSService(URL wsdlLocation) {
        super(wsdlLocation, SEGURIDADWSSERVICE_QNAME);
    }

    public SeguridadWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SeguridadWSService(String wsdlDocumentLocationPath, QName serviceName) {
        super(wsdlDocumentLocationPath, serviceName);
    }

    public SeguridadWSService(String wsdlDocumentLocationPath) {
        super(wsdlDocumentLocationPath, SEGURIDADWSSERVICE_QNAME);
    }

    public SeguridadWSService(String wsdlDocumentLocationPath, String namespaceUri) {
        super(wsdlDocumentLocationPath, getQName(namespaceUri, LOCAL_PART));
    }

    private static QName getQName(String namespaceUri, String localPart) {
        NAME_SPACE_URI=namespaceUri;
        SEGURIDADWSSERVICE_QNAME = new QName(namespaceUri, localPart);
        return SEGURIDADWSSERVICE_QNAME;
    }

    /**
     *
     * @return returns SeguridadWS
     */
    @WebEndpoint(name = "SeguridadWSPort")
    public SeguridadWS getSeguridadWSPort() {
        return super.getPort(new QName(NAME_SPACE_URI, WS_PORT), SeguridadWS.class);
    }

    /**
     *
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to
     * configure on the proxy. Supported features not in * * *
     * the <code>features</code> parameter will have their default values.
     * @return returns SeguridadWS
     */
    @WebEndpoint(name = "SeguridadWSPort")
    public SeguridadWS getSeguridadWSPort(WebServiceFeature... features) {
        return super.getPort(new QName(NAME_SPACE_URI, WS_PORT), SeguridadWS.class, features);
    }
}
