package org.kudytech.workflow.ws.client;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import org.kudytech.ws.client.utils.AbstractWebServiceProvider;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.6-1b01 Generated
 * source version: 2.2
 *
 */
@WebServiceClient(
        name = "WorkFlowWSService",
targetNamespace = "http://ws.webservices.workflow.adeamx.com/",
wsdlLocation = "http://localhost:6680/adea-compras-ws/Workflow?wsdl")
public class WorkFlowWSService
        extends AbstractWebServiceProvider {

    private static QName WORKFLOWWSSERVICE_QNAME =
            new QName("http://ws.webservices.workflow.adeamx.com/", "WorkFlowWS");
    private static final String LOCAL_PART = "WorkFlowWS";
    private static String NAME_SPACE_URI = "http://ws.webservices.workflow.adeamx.com/";
    private static final String WS_PORT = "WorkFlowWSPort";

    public WorkFlowWSService(URL wsdlLocation) {
        super(wsdlLocation, WORKFLOWWSSERVICE_QNAME);
    }

    public WorkFlowWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WorkFlowWSService(String wsdlDocumentLocationPath, QName serviceName) {
        super(wsdlDocumentLocationPath, serviceName);
    }

    public WorkFlowWSService(String wsdlDocumentLocationPath) {
        super(wsdlDocumentLocationPath, WORKFLOWWSSERVICE_QNAME);
    }

    public WorkFlowWSService(String wsdlDocumentLocationPath, String namespaceUri) {
        super(wsdlDocumentLocationPath, getQName(namespaceUri, LOCAL_PART));
    }

    private static QName getQName(String namespaceUri, String localPart) {
        NAME_SPACE_URI = namespaceUri;
        WORKFLOWWSSERVICE_QNAME = new QName(namespaceUri, localPart);
        return WORKFLOWWSSERVICE_QNAME;
    }

    /**
     *
     * @return returns WorkFlowWS
     */
    @WebEndpoint(name = "WorkFlowWSPort")
    public WorkFlowWS getWorkFlowWSPort() {
        return super.getPort(new QName(NAME_SPACE_URI, WS_PORT), WorkFlowWS.class);
    }

    /**
     *
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to
     * configure on the proxy. Supported features not in * * *
     * the <code>features</code> parameter will have their default values.
     * @return returns WorkFlowWS
     */
    @WebEndpoint(name = "WorkFlowWSPort")
    public WorkFlowWS getWorkFlowWSPort(WebServiceFeature... features) {
        return super.getPort(new QName(NAME_SPACE_URI, WS_PORT), WorkFlowWS.class, features);
    }
}
